#!/bin/bash
#SBATCH -t 20:00:00
#SBATCH --mem=128G
#SBATCH --cpus-per-task=8
#SBATCH -o mpmap.log
#SBATCH -e mpmap.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=c.j.r.jiang@umcutrecht.nl

REF_PREFIX=minigraph_cactus_grch38_f1_clip_d9_m1k_D10M_m1k_cat_gencode38_vgrna_k32
OUT_PREFIX=

vg mpmap -t 8 \
-n rna \
-M 1 \
--agglomerate-alns -x ${REF_PREFIX}.xg \
-g ${REF_PREFIX}.gcsa \
-d ${REF_PREFIX}.dist \
-f <(cat sim_mc_grch38_hg002_vgrna_k32_h1_1.fq.gz sim_mc_grch38_hg002_vgrna_k32_h2_1.fq.gz)\
-f <(cat sim_mc_grch38_hg002_vgrna_k32_h1_2.fq.gz sim_mc_grch38_hg002_vgrna_k32_h2_2.fq.gz) > ${OUT_PREFIX}.gamp



file="sra_ids.txt"

array=()
while IFS=' ' read -ra line; do
    array+=("${line[@]}")
done < "$file